ChatApp/ViewComponents/RoomViewComponent.cs
using ChatApp.Database;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Linq;
using System.Security.Claims;

namespace ChatApp.ViewComponents
{
    public class RoomViewComponent : ViewComponent
    {
        private readonly AppDbContext _ctx;

        public RoomViewComponent(AppDbContext ctx)
        {
            _ctx = ctx;
        }

        public IViewComponentResult Invoke()
        {
            var userId = HttpContext.User.FindFirst(ClaimTypes.NameIdentifier).Value;
            var chats = _ctx.ChatUsers
                .Include(x=>x.Chat)
                .Where(x => x.UserId == userId)
                .Select(x=>x.Chat)
                .ToList();
            return View(chats);
        }
    }
}

ChatApp/Views/Shared/_Layout.cshtml
<!Doctype html>
<html lang="en">

<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <meta http-equiv="X-UA-Compatible" content="ie=edge"/>
    <title>ChatApp</title>
    <link href="~/css/site.css" rel="stylesheet" />
</head>

<body>

    <div class="navbar">
        
    </div>

    <div class="main">
        @if(User.Identity.IsAuthenticated)
        { 
            <vc:room></vc:room>
        }
        <div class="chat">
            @RenderBody()
        </div>

        <div class="modal" id="create-room-modal">
            <form asp-controller="Home" 
                  asp-action="CreateRoom"
                  class="modal-body">
                <button type="button" class="close" onclick="closeModal()">X</button>
                <header>Create Room</header>
                <div>
                    <input name="name"/>
                </div>
                <footer>
                    <button>Create</button>
                </footer>
            </form>
        </div>
    </div>

    <script src="~/js/site.js"></script>
    @RenderSection("Scripts", false)

</body>

</html>